[book]
authors = ["Robert Guthrie"]
language = "en"
multilingual = false
src = "src"
title = "ORIC Loomio Guide"

[output.html]
no-section-label = true
edit-url-template = "https://github.com/loomio/loomio-docs/edit/main/oric/{path}"
