[book]
authors = ["Robert Guthrie"]
language = "en"
multilingual = false
src = "src"
title = "Applying Loomio"

[output.html]
no-section-label = true
edit-url-template = "https://github.com/loomio/loomio-docs/edit/main/guides/{path}"
site-url = "/en/guides/"
