name: github pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v2

      - name: Setup mdBook
        uses: peaceiris/actions-mdbook@v1
        with:
          mdbook-version: '0.4.12'

      - run: mdbook build user_manual
      - run: mdbook build guides
      - run: mdbook build policy
      - run: mdbook build oric
      - run: mkdir ./public
      - run: cp -R static/* ./public/
      - run: mv ./user_manual/book ./public/en/user_manual
      - run: mv ./guides/book ./public/en/guides
      - run: mv ./policy/book ./public/en/policy
      - run: mv ./oric/book ./public/en/oric

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
